---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-component-kyma-project-io-v1alpha1-manifest
  failurePolicy: Fail
  name: mmanifest.kb.io
  rules:
  - apiGroups:
    - operator.kyma-project.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - manifests
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-component-kyma-project-io-v1alpha1-manifest
  failurePolicy: Fail
  name: vmanifest.kb.io
  rules:
  - apiGroups:
    - operator.kyma-project.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - manifests
  sideEffects: None
