apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: controller-manager
  namespace: system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
          - /metrics
          - /v1*
  selector:
    matchLabels:
      app.kubernetes.io/component: module-manager.kyma-project.io