apiVersion: operator.kyma-project.io/v1alpha1
kind: Watcher
metadata:
  name: watcher
  namespace: system
  labels:
    operator.kyma-project.io/managed-by: "module-manager"
spec:
  labelsToWatch:
    operator.kyma-project.io/watched-by: "module-manager"
  field: "status"
  serviceInfo:
    name: event-service
    port: 8082
    namespace: system

---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: system
spec:
  selector:
    app.kubernetes.io/name: module-manager
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082