apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: controller-resources-metrics
  files:
  - controller-resources-metrics.json
- name: controller-runtime-metrics
  files:
  - controller-runtime-metrics.json
