# The main purpose of this dedicated kustomization is to have separate resources configuration for load tests. Unlike the default setup, it enables the ability to configure additional components that we do not want in the default configuration (e.g. vendor-specific gateway implementation) but want to test for load anyhow.
resources:
  - metrics_cluster_role_binding.yaml
  - metrics_role.yaml
  - metrics_role_binding.yaml
  - ../manager
generatorOptions:
  disableNameSuffixHash: true

# Adds namespace to all resources.
namespace: kcp-system
namePrefix: kmm-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/component: module-manager.kyma-project.io
  app.kubernetes.io/instance: module-manager-main
  app.kubernetes.io/name: module-manager
  app.kubernetes.io/created-by: kustomize
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: manual-deployment


patchesStrategicMerge:
  # We expect an istio gateway to be already present in KCP
  - patches/adjust_resources_in_deployment.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --max-concurrent-reconciles=200            
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --rate-limiter-burst=500      
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --rate-limiter-frequency=200
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --workers-concurrent-manifest=100
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --k8s-client-qps=300
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --k8s-client-burst=300      
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --enable-pprof=true
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --check-ready-states=true  
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/serviceInfo/name
        value: kmm-event-service      
      - op: replace
        path: /spec/serviceInfo/namespace
        value: kcp-system
    target:
      group: operator.kyma-project.io
      version: v1alpha1
      kind: Watcher

components:
  - ../crd
  - ../rbac
  # [WATCHER] To enable the watcher, uncomment all the sections with [WATCHER]
  - ../watcher
  # [ISTIO] To enable istio, uncomment all sections with 'ISTIO'.
  - ../istio
  # [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
  # crd/kustomization.yaml
  #- ../webhook
  # [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'. 'WEBHOOK' components are required.
  #- ../certmanager
  # [PROMETHEUS] To enable prometheus monitor, uncomment all sections with 'PROMETHEUS'.
  - ../prometheus
  # [GRAFANA] To generate configmap for provision grafana dashboard
  - ../grafana