resources:
- manager.yaml
- gateway.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: eu.gcr.io/kyma-project/module-manager
  newTag: 6ba23a71
