resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

images:
- name: controller
  newName: eu.gcr.io/kyma-project/module-manager
  newTag: 6ba23a71
